### ISSUE TITLE
Are you available for freelancing?

### ISSUE THREAD

**Issue by deepseek** [ChandlerBang/awesome-graph-attack-papers#2]
@ChandlerBang 
Hi there,
i have a task that i want to solve using machine learning, 
are you interested in freelancing?

what is your email so that i can discuss with you with details,
waiting for your reply

**Comment by ChandlerBang** [comment]
Hi deepseek,

I am sorry that currently I am occupied with several research projects and not available for the collaboration.

Thanks for understanding.
