### ISSUE TITLE
Add attack paper

### ISSUE THREAD

**Issue by sigeisler** [ChandlerBang/awesome-graph-attack-papers#3]
Hi,

it would be great if you could list our recent workshop paper:

[Simon Geisler (Technical University of Munich)*; Daniel Zügner (Technical University of Munich); Aleksandar Bojchevski (Technical University of Munich); Stephan Günnemann (Technical University of Munich). Attacking Graph Neural Networks at Scale](https://www.dropbox.com/s/ddrwoswpz3wwx40/Robust_GNNs_at_Scale__AAAI_Workshop_2020_CameraReady.pdf?dl=0)

That would be awesome! Thanks in advance and for maintaining this helpful overview!

**Comment by ChandlerBang** [comment]
Sure, I have added it. Nice work!
