### ISSUE TITLE
Please add our new backdoor attack paper  by RAID 2022

### ISSUE THREAD

**Issue by goodman1204** [ChandlerBang/awesome-graph-attack-papers#5]
Hi @ChandlerBang, 

It will be great if you can add our latest graph backdoor paper accepted by RAID 2022, 

"Transferable Graph Backdoor Attack. Shuiqiao Yang, Bao Gia Doan, Paul Montague, Olivier De Vel, Tamas Abraham, Seyit Camtepe, Damith C. Ranasinghe, Salil S. Kanhere" 

URL: https://arxiv.org/abs/2207.00425
Thanks.

**Comment by ChandlerBang** [comment]
Hey, thanks for the reminder and I just added your paper in the latest commit. I am sorry for the late reply since I was busy with other projects.

**Comment by goodman1204** [comment]
It's ok, thanks for your help @ChandlerBang
