### ISSUE TITLE
Add a defense paper

### ISSUE THREAD

**Issue by Xiuyu-Li** [ChandlerBang/awesome-graph-attack-papers#7]
It would be great if you can add our recent paper covering a scalable defense accepted by Learning on Graphs (LoG) 2022:
**GARNET: Reduced-Rank Topology Learning for Robust and Scalable Graph Neural Networks** [[paper]](https://openreview.net/forum?id=kvwWjYQtmw) [[code]](https://github.com/cornell-zhang/GARNET) by Chenhui Deng, Xiuyu Li, Zhuo Feng, Zhiru Zhang

Thank you!

**Comment by ChandlerBang** [comment]
Sure. I just added it. (please discard my previous message)
